### ISSUE TITLE
[Meta] Moteur de recherche global

### ISSUE THREAD

**Issue by Spone** [telabotanica/naturadapt#291]
- [x] #292
- [ ] #293
- [ ] #294
- [x] Indexer les actualités
- [x] Indexer les utilisateurs
- [x] Indexer les documents
- [x] Indexer les messages des discussions
- [ ] #297
- [x] #295
- [ ] #296
- [x] #299
- [x] #300
- [x] #298
- [x] #301
- [x] #306
- [x] #307

-----

## Évolutions possibles

- [ ] Résultats sans rechargement de page
- [ ] Indexer le contenu des documents (PDF uniquement)
